[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.4",
    "alembic-postgresql-enum>=1.10.0",
    "bcrypt>=5.0.0",
    "cloudinary>=1.44.2",
    "fastapi[standard]>=0.136.1",
    "httpx>=0.28.1",
    "langchain-groq>=1.1.2",
    "numpy>=2.4.4",
    "passlib[bcrypt]==1.7.4",
    "pillow>=12.2.0",
    "psycopg2-binary>=2.9.12",
    "pydantic-settings>=2.14.0",
    "pydantic[email]>=2.13.3",
    "pyjwt>=2.12.1",
    "python-jose>=3.5.0",
    "python-multipart>=0.0.27",
    "python-slugify>=8.0.4",
    "redis>=7.4.0",
    "requests>=2.33.1",
    "scipy>=1.17.1",
    "sentry-sdk>=2.58.0",
    "sqlalchemy>=2.0.49",
    "uvicorn[standard]>=0.46.0",
]
[tool.fastapi]
# This ensures the root search path is the current directory
# so that 'from app.x import y' works correctly.
path = "."
app = "app.main:app"
