"""to add summary as ai feautre

Revision ID: 2287b1723726
Revises: 986f6ca57e7d
Create Date: 2026-04-27 20:50:51.441919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2287b1723726'
down_revision: Union[str, Sequence[str], None] = '986f6ca57e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'summary')
    # ### end Alembic commands ###
