"""to add super admin and removed unwantedthings 

Revision ID: 5cecb28759f9
Revises: 02adb3ee7090
Create Date: 2026-05-04 22:32:53.243618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cecb28759f9'
down_revision: Union[str, Sequence[str], None] = '02adb3ee7090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_create_tags_id'), table_name='create_tags')
    op.drop_index(op.f('ix_create_tags_name'), table_name='create_tags')
    op.drop_table('create_tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('create_tags',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('create_tags_pkey'))
    )
    op.create_index(op.f('ix_create_tags_name'), 'create_tags', ['name'], unique=True)
    op.create_index(op.f('ix_create_tags_id'), 'create_tags', ['id'], unique=False)
    # ### end Alembic commands ###
