"""to add user use tags by admin 

Revision ID: 5e92bf1b6158
Revises: 5727afce64c7
Create Date: 2026-05-04 20:35:04.873986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e92bf1b6158'
down_revision: Union[str, Sequence[str], None] = '5727afce64c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('create_tags',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_create_tags_id'), 'create_tags', ['id'], unique=False)
    op.create_index(op.f('ix_create_tags_name'), 'create_tags', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_create_tags_name'), table_name='create_tags')
    op.drop_index(op.f('ix_create_tags_id'), table_name='create_tags')
    op.drop_table('create_tags')
    # ### end Alembic commands ###
