"""to add corn in post model 

Revision ID: 6fa9c12cb7f9
Revises: 2e7afa3744a7
Create Date: 2026-05-06 23:07:49.861582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa9c12cb7f9'
down_revision: Union[str, Sequence[str], None] = '2e7afa3744a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('trending_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'trending_score')
    # ### end Alembic commands ###
