"""fix name issue

Revision ID: 79d65e04abab
Revises: e8ef4664670a
Create Date: 2026-05-02 21:38:27.716415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d65e04abab'
down_revision: Union[str, Sequence[str], None] = 'e8ef4664670a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('likes_author_id_fkey'), 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('likes', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('likes_author_id_fkey'), 'likes', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('likes', 'user_id')
    # ### end Alembic commands ###
