"""to fix mdoel issue

Revision ID: def3912163c4
Revises: 751836c8a025
Create Date: 2026-05-06 22:05:38.975779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def3912163c4'
down_revision: Union[str, Sequence[str], None] = '751836c8a025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('slug', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('communities_description_key'), 'communities', type_='unique')
    op.create_unique_constraint(None, 'communities', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'communities', type_='unique')
    op.create_unique_constraint(op.f('communities_description_key'), 'communities', ['description'], postgresql_nulls_not_distinct=False)
    op.drop_column('communities', 'slug')
    # ### end Alembic commands ###
