/* ─── Design Tokens (shared across all Home sub-components) ─── */
export const T = {
  bg: "#fafaf8",
  surface: "#ffffff",
  surfaceEl: "#f5f4f0",
  border: "rgba(0,0,0,0.07)",
  borderMed: "rgba(0,0,0,0.12)",
  violet: "#7c3aed",
  violetLight: "#ede9fe",
  violetMid: "#ddd6fe",
  rose: "#e11d48",
  roseLight: "#ffe4e6",
  amber: "#d97706",
  amberLight: "#fef3c7",
  emerald: "#059669",
  emeraldLight: "#d1fae5",
  cyan: "#0891b2",
  cyanLight: "#cffafe",
  orange: "#ea580c",
  orangeLight: "#ffedd5",
  text: "#0f0e0c",
  text2: "#44403c",
  text3: "#78716c",
  text4: "#a8a29e",
  shadow: "0 1px 3px rgba(0,0,0,0.08), 0 8px 24px rgba(0,0,0,0.06)",
  shadowHover: "0 4px 12px rgba(0,0,0,0.1), 0 20px 48px rgba(0,0,0,0.12)",
};

export const catMeta = {
  Technology: { color: T.violet, bg: T.violetLight },
  Music: { color: T.rose, bg: T.roseLight },
  Sustainability: { color: T.emerald, bg: T.emeraldLight },
  "Art & Design": { color: T.orange, bg: T.orangeLight },
  Wellness: { color: T.emerald, bg: T.emeraldLight },
  Photography: { color: T.cyan, bg: T.cyanLight },
  "Food & Drink": { color: T.amber, bg: T.amberLight },
  Networking: { color: T.violet, bg: T.violetLight },
  Education: { color: T.amber, bg: T.amberLight },
};

export const badgeColors = {
  Trending: { bg: T.violetLight, color: T.violet },
  Hot: { bg: T.roseLight, color: T.rose },
  "Near You": { bg: T.emeraldLight, color: T.emerald },
  "Sold Out Soon": { bg: T.amberLight, color: T.amber },
};

export const events = [
  {
    id: 1,
    title: "Tech Frontier Summit",
    date: "Jun 12–14",
    loc: "San Francisco, CA",
    cat: "Technology",
    img: "https://images.unsplash.com/photo-1540575861501-7cf05a4b125a?auto=format&fit=crop&w=700&q=80",
    price: "$299",
    speakers: [
      "https://i.pravatar.cc/32?img=1",
      "https://i.pravatar.cc/32?img=2",
      "https://i.pravatar.cc/32?img=3",
    ],
    rating: "4.9",
    badge: "Trending",
    nearYou: false,
    mode: "In-person",
    excerpt: "Keynotes & workshops with leading platform teams.",
    attendees: 2400,
    capacity: 2600,
  },
  {
    id: 2,
    title: "Global Jazz Initiative",
    date: "Jul 05",
    loc: "London, UK",
    cat: "Music",
    img: "https://images.unsplash.com/photo-1514525253344-991c70cdc0d9?auto=format&fit=crop&w=700&q=80",
    price: "Free",
    speakers: [
      "https://i.pravatar.cc/32?img=4",
      "https://i.pravatar.cc/32?img=5",
    ],
    rating: "4.7",
    badge: null,
    nearYou: false,
    mode: "In-person",
    excerpt: "Evening sets and curator-led listening sessions.",
    attendees: 890,
    capacity: 1100,
  },
  {
    id: 3,
    title: "Green Future Expo",
    date: "Aug 20",
    loc: "Berlin, DE",
    cat: "Sustainability",
    img: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=700&q=80",
    price: "$45",
    speakers: [
      "https://i.pravatar.cc/32?img=6",
      "https://i.pravatar.cc/32?img=7",
    ],
    rating: "4.8",
    badge: "Hot",
    nearYou: false,
    mode: "Hybrid",
    excerpt: "Expo floor + virtual policy roundtables.",
    attendees: 1200,
    capacity: 1400,
  },
  {
    id: 4,
    title: "Neon Art Collective",
    date: "Sep 02",
    loc: "Tokyo, JP",
    cat: "Art & Design",
    img: "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?auto=format&fit=crop&w=700&q=80",
    price: "$89",
    speakers: [
      "https://i.pravatar.cc/32?img=9",
      "https://i.pravatar.cc/32?img=10",
    ],
    rating: "5.0",
    badge: "Sold Out Soon",
    nearYou: false,
    mode: "In-person",
    excerpt: "Installations and late-night immersive sets.",
    attendees: 1420,
    capacity: 1500,
  },
  {
    id: 5,
    title: "Morning Yoga in the Park",
    date: "May 10",
    loc: "Lucknow, IN",
    cat: "Wellness",
    img: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=700&q=80",
    price: "Free",
    speakers: ["https://i.pravatar.cc/32?img=11"],
    rating: "4.6",
    badge: "Near You",
    nearYou: true,
    mode: "In-person",
    excerpt: "Sunrise flows in the amphitheatre — mats provided.",
    attendees: 80,
    capacity: 120,
  },
  {
    id: 6,
    title: "Street Photography Walk",
    date: "May 12",
    loc: "Lucknow, IN",
    cat: "Photography",
    img: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?auto=format&fit=crop&w=700&q=80",
    price: "₹199",
    speakers: [
      "https://i.pravatar.cc/32?img=12",
      "https://i.pravatar.cc/32?img=13",
    ],
    rating: "4.9",
    badge: "Near You",
    nearYou: true,
    mode: "In-person",
    excerpt: "Guided golden-hour route with local historians.",
    attendees: 24,
    capacity: 35,
  },
  {
    id: 7,
    title: "Indie Food Festival",
    date: "May 18",
    loc: "Lucknow, IN",
    cat: "Food & Drink",
    img: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=700&q=80",
    price: "₹499",
    speakers: [],
    rating: "4.7",
    badge: "Near You",
    nearYou: true,
    mode: "In-person",
    excerpt: "Tasting lanes, brewery collabs, and live demos.",
    attendees: 620,
    capacity: 900,
  },
  {
    id: 8,
    title: "AI Research Forum 2026",
    date: "Oct 15",
    loc: "Online",
    cat: "Technology",
    img: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?auto=format&fit=crop&w=700&q=80",
    price: "$120",
    speakers: [
      "https://i.pravatar.cc/32?img=14",
      "https://i.pravatar.cc/32?img=15",
    ],
    rating: "4.6",
    badge: "Trending",
    nearYou: false,
    mode: "Virtual",
    excerpt: "Parallel tracks on evals, safety, and infra at scale.",
    attendees: 2100,
    capacity: 5000,
  },
];
